### ISSUE TITLE
Hello buddy, I caught a Bug

### ISSUE THREAD

**Issue by EJDouglas** [josenriagu/ubiquitous-tribble#23]
**Describe the bug**
There is a typo in the "About Me" section. Instead of "me love" in the second sentence, it should be "I love building functional teams".  I wasn't sure if this was meant to be an inside joke for coders or not. If so, please ignore. Good job!

**To Reproduce**
1. Go to '...' - "About Me"
2. Click on '....' "say.hello()"
3. Scroll down to '....' "Hallo...Me love.."

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - I use iOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josenriagu** [comment]
Hello buddy, thanks for creating the issue.
Yes, that was my informal way of saying "I love ..." (it's written same way on my Github profile too). I felt like not making the portfolio too formal. Haha

I really appreciate you for taking your time to visit my website.🙌
Cheers🍻
